### ISSUE TITLE
Factor out CmdLine support and make it optional

### ISSUE THREAD

**Issue by fryguybob** [diagrams/diagrams-cairo#29]
This should involve all the backends.  There is a lot of redundancy in backend command line support that should be factored out into a separate package.  Additionally there are use cases (such as GHCJS) that would just as well not have command line support so there should be a cabal flag to make it optional (or perhaps some abstraction that would make it useful in that setting).

**Comment by byorgey** [comment]
I think this has been done.  Please re-open if I am wrong, or maybe open a new ticket if this has mostly been done but there is some piece of it we would still like to do.
