### ISSUE TITLE
Split out auto-recompilation into a standalone tool using hint

### ISSUE THREAD

**Issue by fryguybob** [diagrams/diagrams-cairo#5]
(Imported from <http://code.google.com/p/diagrams/issues/detail?id=16>. Original issue from byor...@gmail.com on April  2, 2011, 06:07:57 PM UTC)

See the #diagrams IRC logs from 1 April 2011 for some ideas on what could be done here.

**Comment by byorgey** [comment]
Yes, I think this can be closed now.  I think some of the code referenced above made its way into `diagrams-builder`, and the auto-recompilation is now handled by `Diagrams.Backend.CmdLine` in `diagrams-lib`.
