### ISSUE TITLE
Travis build broken

### ISSUE THREAD

**Issue by FranklinChen** [diagrams/diagrams-cairo#61]
The Travis build appears to currently be broken. (I noticed this while failing to install `diagrams-cairo` using GHC 7.10.1.)

**Comment by bergey** [comment]
As far as GHC 7.10, `cairo` only recently fixed https://github.com/gtk2hs/gtk2hs/issues/88, and hasn't yet released to Hackage.  I haven't had a chance to test `diagrams-cairo` since then.

**Comment by byorgey** [comment]
The latest `gtk` release was uploaded in July, which hopefully means we can close this?

**Comment by bergey** [comment]
I believe so.  I've been using 7.10 for months, and making changes to `diagrams-cairo` this week, and haven't noticed any problems.

**Comment by FranklinChen** [comment]
Yeah, this seems to be all good now.
