### ISSUE TITLE
GHC 7.10 support on hackage

### ISSUE THREAD

**Issue by gibiansky** [diagrams/diagrams-cairo#62]
Could we get a new release on Hackage? The latest Hackage version doesn't allow base 4.8, and so doesn't work with GHC 7.10.

**Comment by bergey** [comment]
As far as I know `cairo` doesn't compile on GHC-7.10 - they only recently fixed gtk2hs/gtk2hs#88, and have't yet released to Hackage.

**Comment by gibiansky** [comment]
Ah, my apologies – I assumed that since `cairo` allowed `base-4.8` and the Github version of `diagrams-cairo` had been bumped to allow it, it was just waiting on a Hackage bump.

**Comment by sumitsahrawat** [comment]
I was able to build `cairo-0.13.1.0` with GHC 7.10.
According to hackage, it was uploaded on March 1, 2015.

**Comment by cchalmers** [comment]
This reminds me, I started an `ihaskell-diagrams` that doesn't depend on Cairo. https://github.com/cchalmers/ihaskell-diagrams if anyone's interested.

**Comment by gibiansky** [comment]
Are there any downsides to not using cairo? If there aren't, or they are
not very significant, I'd be happy to merge that into ihaskell-diagrams
master. Or if there are some downsides, put it as a flag enabled by default.

**Comment by byorgey** [comment]
Well, it used to be that the cairo backend was the only one that really supported everything and could produce raster output.  But especially now that the Rasterific backend is fairly mature, that is no longer true.

**Comment by cchalmers** [comment]
Yeah, I don't think Cairo's advantages are significant. I might add it as an optional backend and make a PR after 1.3 is released.

**Comment by bergey** [comment]
Text is the big one, I think.  I'm not sure about all the other Backends, but I think Cairo still has the best story for font selection, proper kerning, and especially non-Latin scripts.  Maybe `-pgf` is as good at some of those.

**Comment by cchalmers** [comment]
The `pgf` backend has excellent font support but you have to write the Tex code yourself. Another problem is it outputs PDFs so it would probably need an external dependency to convert to use with `ihaskell`.

Cairo's font support is certainly better than rasterific and svg. I still don't think it's enough depend on Cairo as default.

**Comment by byorgey** [comment]
As far as I can tell this has been fixed since the `1.3` release.
