### ISSUE TITLE
Relax version boundry on base for version 1.4 

### ISSUE THREAD

**Issue by eggzilla** [diagrams/diagrams-cairo#69]
Hi,
could you please relax the upper version bound of diagrams-cairo-1.4 for the base library from base (>=4.2 && <4.10) to base (>=4.2 && <4.11) maybe with a revision on hackage. I tested building with the relaxed constraint on archlinux with GHC-8.2.1 and it worked flawlessly. Thanks for your work on diagrams!
Best wishes
Florian

**Comment by byorgey** [comment]
Thanks for the nudge, I will try to get to this soon.  I've been slowly working through a backlog of packages that need bumping.

**Comment by eggzilla** [comment]
Thanks for the quick response and for your help!

**Comment by byorgey** [comment]
I've now done a test build and bumped the `base` upper bound on Hackage, so it should build under GHC-8.2 now.  I also bumped the `optparse-applicative` upper bound while I was at it.  Thanks for your patience, and let us know if you run into any other issues!

**Comment by eggzilla** [comment]
Thanks for the quick help !
