### ISSUE TITLE
Too strict version bounds on optparse-applicative and base

### ISSUE THREAD

**Issue by sternenseemann** [diagrams/diagrams-cairo#77]
Confirmed to build with optparse-applicative 0.16.1.0 and base 4.14.1.0.

**Comment by byorgey** [comment]
Thanks for the nudge.  Working on getting an updated package released now.

**Comment by byorgey** [comment]
`diagrams-cairo` has now been revised on Hackage to build with these packages (and hence with GHC 8.10).  As for GHC 9.0, note that the `cairo` package itself does not yet compile with GHC 9.0.
